#!/usr/bin/env python3
"""Regenerates docs/roadmap.svg from the STEPS table below (no dependencies).

Edit the status of a step here, run `python3 docs/tools/make_roadmap.py` from the repo root, commit the SVG.
Status: "done" (green), "partial" (amber), "todo" (grey). The numbered steps follow docs/research/03-resto-sistemas.md.
"""
import html
import pathlib

STEPS = [
    ("1", "Base: Release, Ki, Stamina, sync", "done"),
    ("2", "Progression: level, cost curve, weights, gravity", "done"),
    ("3", "Races & classes (JSON); creation screen pending", "partial"),
    ("4", "Skills (JSON); lock-on, swoop, masters pending", "partial"),
    ("5", "Forms per race (JSON); Oozaru/God/instant pending", "partial"),
    ("5b", "Kaioken (branch feature/kaioken, open bug)", "partial"),
    ("6", "Form Mastery rework + double-tap transform", "todo"),
    ("7", "Ki techniques + projectile entity", "todo"),
    ("8", "World: Lookout, dimensions, master NPCs", "todo"),
    ("9", "Death, Other World, alignment", "todo"),
    ("10", "Sagas / missions engine", "todo"),
    ("11", "Dragon Balls, wishes, Senzu, scouter", "todo"),
    ("12", "Special forms: God, UI, Mystic, Majin absorb, fusion", "todo"),
    ("UI", "Design pass: HUD bars, sheet, auras, textures", "todo"),
]
COLORS = {"done": ("#d9f2e0", "#2e9d57"), "partial": ("#fff1cc", "#d19a00"), "todo": ("#ececec", "#8a8a8a")}
LABEL = {"done": "done", "partial": "partial / in progress", "todo": "planned"}

W, BOX_H, GAP, COLS = 760, 54, 14, 1
LEFT, TOP = 24, 70
height = TOP + len(STEPS) * (BOX_H + GAP) + 50

out = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{height}" viewBox="0 0 {W} {height}" '
       f'role="img" aria-label="Kimon roadmap" font-family="Helvetica, Arial, sans-serif">',
       f'<rect width="{W}" height="{height}" fill="#ffffff"/>',
       f'<text x="{LEFT}" y="34" font-size="22" font-weight="700" fill="#222">Kimon roadmap — the 12 steps of research/03</text>',
       f'<text x="{LEFT}" y="54" font-size="13" fill="#666">Generated by docs/tools/make_roadmap.py · see docs/STATUS.md for details</text>']
for i, (num, text, status) in enumerate(STEPS):
    y = TOP + i * (BOX_H + GAP)
    fill, stroke = COLORS[status]
    out.append(f'<rect x="{LEFT}" y="{y}" width="{W - 2 * LEFT}" height="{BOX_H}" rx="10" fill="{fill}" stroke="{stroke}" stroke-width="2"/>')
    out.append(f'<text x="{LEFT + 18}" y="{y + 33}" font-size="20" font-weight="700" fill="#222">{html.escape(num)}</text>')
    out.append(f'<text x="{LEFT + 70}" y="{y + 33}" font-size="16" fill="#222">{html.escape(text)}</text>')
    out.append(f'<text x="{W - LEFT - 16}" y="{y + 33}" font-size="13" text-anchor="end" fill="{stroke}">{LABEL[status]}</text>')
ly = height - 24
for j, status in enumerate(("done", "partial", "todo")):
    fill, stroke = COLORS[status]
    x = LEFT + j * 190
    out.append(f'<rect x="{x}" y="{ly - 12}" width="16" height="16" rx="4" fill="{fill}" stroke="{stroke}" stroke-width="2"/>')
    out.append(f'<text x="{x + 24}" y="{ly + 1}" font-size="13" fill="#444">{LABEL[status]}</text>')
out.append("</svg>")
path = pathlib.Path(__file__).resolve().parents[1] / "roadmap.svg"
path.write_text("\n".join(out) + "\n", encoding="utf-8")
print(f"wrote {path} ({len(STEPS)} steps)")
